---
title: "Class Imbalance"
author: "Alex Brander"
date: "2026-07-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(caTools)
library(ROSE)
library(readxl)

Telco_Customer_Churn <- read_excel("Telco-Customer-Churn.xlsx")
```

```{r}
churn_12 <- Telco_Customer_Churn%>%
   mutate(
    TotalCharges = na_if(as.character(TotalCharges), ""),
    TotalCharges = as.numeric(TotalCharges),
    Churn = factor(Churn, levels = c("No", "Yes"))
  )%>%
  select(-customerID)%>%
  select(-gender)%>%
  select(-Partner)%>%
  select(-OnlineSecurity)%>%
  select(-TechSupport)%>%
  select(-DeviceProtection)%>%
  select(-OnlineBackup)%>%
  select(-PhoneService)%>%
  drop_na(TotalCharges)%>%
  mutate(across(where(is.character), as.factor))

churn_12$SeniorCitizen <- factor(churn_12$SeniorCitizen, levels= c(0,1), labels = c("No", "Yes"))
```


```{r}
set.seed(619)
split <- sample.split(churn_12$Churn, SplitRatio = 0.80)

train <- subset(churn_12, split)
test <- subset(churn_12, !split)
```


Synthetic Oversampling
```{r}

table(train$Churn)

rose_balanced <- ROSE(Churn~., data= train, N =5625, p= 0.5, seed= 526)

```
```{r}
train_balanced    <- rose_balanced$data


train_balanced$tenure <- round(train_balanced$tenure)

table(train_balanced$Churn)
```


```{r}

summary(balanced_model <- glm(Churn~ Contract + InternetService + tenure + MultipleLines + PaymentMethod + TotalCharges + PaperlessBilling + StreamingTV + StreamingMovies + SeniorCitizen + Dependents + MonthlyCharges, data= train_balanced, family = binomial))

```
```{r}
(exp(balanced_model$coefficients[-1])-1)* 100
```

```{r}
test_prob <- predict(balanced_model, newdata= test, type= "response")

test_pred <- ifelse(test_prob > 0.5, "Yes", "No")

test_pred <- factor(test_pred, levels= c("No", "Yes"))

table(Predicted=test_pred, Actual = test$Churn)

mean(test_pred == test$Churn)
```

